### PR TITLE
Don't force humanize on column names. Provide an option instead

### PR DESCRIPTION
**Pull request by mateusg**
I needed the column names to be exactly how they are on the table, so I made some changes.

### CODE REVIEW

**Comment by Fire-Dragon-DoL** [comment]
I agree with this

**Comment by PlasticLizard** [comment]
This would be very helpful to me as well. Any chance on merging it?

**Comment by brennovich** [comment]
+1

**Comment by ricardodovalle** [comment]
:+1:

**Comment by randym** [comment]
I'm down with the idea, however for backwards compatibility it will need to be :skip_humanization.
I'll add that in today with tests while building support for ActiveRecord > 2.3.8 which, thanks to @straydogstudio, I now know needs to be updated to not use Base#all.

**Comment by randym** [comment]
getting baked in here: https://github.com/randym/acts_as_xlsx/pull/11

**Pull request closed without merging**
